dante.el
Dante currently uses a static string "def" for definitions and "ref" for references, which makes it hard to know which reference you want without cycling through each option. This patch extracts the line that contains the definition/reference as the summary, making navigation easier.
For example, if we run `xref-find-references` in this file
```haskell
module Foo where
f x = x + 1
g y = f y
--    ^ point is here
h z = f z
```
we would now get the following response.
```
/Users/gridaphobe/Source/dante/Foo.hs
3: f x = x + 1
5: g y = f y
7: h z = f z
```
A couple notes:
- I've tried to make things efficient by only reading/traversing each file once, but it might still be slow in a large project. I don't think emacs is particularly fast at slicing and dicing text.
- In multi-file projects I …
=> Improve "summaries" for xref

dante.el
This adds an entry to `dante-repl-command-line-default-methods` that attempts to use Cabal's `new-repl` feature associated with its newer [Nix-style package building system](http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/). I've tested this with a handful of my projects on which I use `new-build` and things seem to work fine for my use-cases, but I haven't put it through a _lot_ of heavy lifting, and there may be edge-cases I haven't yet found.
I also confess that I'm not entirely sure if all the logic here is necessary—and, if it is, whether it should be factored into a helper function like `dante-repl-by-glob` or something—but I'd be happy to make changes of that sort.
=> Add a command line method for Cabal's new-repl mode

dante.el
Does some stuff if I manually call company-dante while writing some code.
---
Can someone test this out? I'm wondering if the Haskell Spacemacs layer doesn't have Company configured correctly.
=> Copy some company-mode code from Intero

dante.el
Emacs-Lisp is a Lisp-2 so the call the continuation must use `funcall`
=> Fix continuation call in `dante-check` when dante is interrupted

dante.el
Fixes #70. May not be the best idea (do `.cabal` dirs exist elsewhere?).
=> Cabal regex fix

dante.el
This way Emacs won't scream at you every time you add a new one, or fill your `custom-set-variables` with garbage.
=> Mark local `dante-project-root` and `dante-target` as safe.

dante.el
The current `dante-fontify-expression` ignores only `haskell-mode-hook`. The `prog-mode-hook` and any other hooks of parent modes are still loaded. I have added a few functions to `prog-mode-hook`, like `whitespace-mode`. So the results of `dante-info` look weird (see the picture below).
In this commit, the function ignores all mode hooks with `delay-mode-hook`. (See http://emacs.stackexchange.com/a/5408/227.)
`dante-info` before this commit:
`dante-info` after this commit:
BTW, thanks for this awesome package!
=> Run haskell-mode without any hooks

dante.el
Right now we cannot call `dante-company` through `M-x` or a key binding to manually start this backend. So I think it might be useful to make it an interactive function.
Thanks!
=> Make dante-company interactive

dante.el
These should be given precedence in this case.
=> Give cabal.project precedence over *.cabal in finding the root

dante.el
Does two things:
- Try to look for a package name in the cabal file to pass to ```cabal new-repl``` (it needs this in multi-packages projects).
- Prioritize "impure" nix over "pure" nix. The default haskell env does not provide a cabal binary. We should look for this in the parent environment if possible. In addition, I don't see the advantage of pure nix shell in this case when we are only using this for a single process, it either works or not. You can always reconfigure this with dante-methods, however.
=> New dante package name, reorder methods

dante.el
If `dante-company` declines to perform completions, then subsequent company backends can take their turn. This includes the standard `company-capf` backend which checks `completion-at-point-functions`: haskell-mode provides such functions for completing LANGUAGE and other
pragmas.
This change makes Dante's company backend decline to complete inside comments, which tackles the specific case of pragma completion as requested in https://github.com/jyp/dante/issues/37 but without adding functionality to Dante itself.
Dante should arguably not complete inside a string either, but I have not implemented that here. (One would check for `(nth 4 (syntax-ppss))`.)
=> Don't complete inside comments, which allows haskell-mode to complete pragmas

dante.el
Dante's flychecker currently reports "no errors" in the case where a module cannot even be compiled because it depends on another broken source file. This leads to mistrust of the checker because clearly-invalid syntax can appear to be considered valid.
For a while now Flycheck has had a mechanism for allowing such "upstream" errors to be nominally reported in the current buffer (on the first line) if they are at least
`flycheck-relevant-error-other-file-minimum-level`. All that is necessary for checkers to support this is for them to parse and return errors for the current buffer where the `:filename` is a different file.
This commit makes such a (minimal) change to the Dante checker, bringing its behaviour into line with comparable checkers such as the Elm and Intero checkers.
(Note …
=> Support flycheck's ability to show "other file" errors

README.org
No eldoc support was a deal breaker for me, but then I discovered that you can actually get the same advantages offered by eldoc by modifying dante-tap-type-time. I think this should be mentioned in the comparison
=> Dante can show type signatures in minibuffer

dante.el
On my GHCi interpreter, the “Compiling \<module\>” notification isn’t always followed by some status message, i.e. not always of the form e.g. `[1 of 1] Compiling Lib [flags changed]`. For example,
```
*Lib> :r
[1 of 1] Compiling Lib
<dir_name>/Lib.hs:15:3: error:
parse error (possibly incorrect indentation or mismatched brackets)
|
15 |   Right rel <- withTransaction dbconn $ do
|   ^
Failed, no modules loaded.
```
Without rejecting the newline match, the progress regex (`^\\[\\([0-9]*\\) of \\([0-9]*\\)\\] Compiling \\([^ ]*\\).*`) will thus match the next two lines, i.e. the 3rd capture group will match
```
Lib
<dir_name>/Lib.hs:15:3:
```
As a result, the error message is gone, and flycheck reports no errors.
=> Reject newline match in module names

dante.el
This adds support for [snack](https://github.com/nmattia/snack).
From *Why should I use Snack?*:
> 1. The same build tool is used by developers and on CI.
> 2. The build tool guarantees that builds are reproducible.
> 3. The builds are incremental, i.e. if a library contains 300 modules and I modify the main function, only the Main module will be rebuilt.
> 
> Using Cabal inside of Nix solves (2); however this means that the builds are not incremental anymore (3). This may not be a problem on CI but definitely is when developing locally. The way to work around that is to use Cabal inside a nix-shell locally and call cabal2nix on CI. This means that developers use a different tool locally than on CI (1). Moreover, a lot of projects nowadays use Stack and, somewhat more importantly, …
=> Add snack to dante-methods

dante.el
Sometimes error message contain paths to the file being checked, e.g. /tmp/tmp/Tests.hs within
```
error: [-Wdeferred-type-errors]
• Occurs check: cannot construct the infinite type: t ~ t -> Int
• In the first argument of ‘d’, namely ‘d’
In the second argument of ‘(*)’, namely ‘d d’
In the second argument of ‘(+)’, namely ‘c * d d’
• Relevant bindings include
d :: t -> Int (bound at /tmp/tmp/Test.hs:33:14)
go :: Int -> Int -> Int -> (t -> Int) -> Int
(bound at /tmp/tmp/Test.hs:33:5)
```
I think it's good idea to have the paths point to the original file rather than a temporary one.
=> Clean up temporary file names in error message body

dante.el
This helps flycheck to resolve relative file names in errors messages. When dependencies of current module have errors they get reported to flycheck but paths are typically relative to the cabal file, at least for `cabal new-*` set of checkers. I think it's unlikely that for other checkers any relative paths would be reported relative to the current module being edited so the fix shoul be reasonable, but I'm not sure whether my fix is good enough for nix-based checkers.
=> Set up working directory for the checker

dante.el
Found that the latest Dante doesn't byte-compile due to an argument number mismatch, and this fix is what I expect the offending piece of code should be.
=> Fix error which breaks byte compilation and runtime

README.org
I think it is a really cool feature, but it is really hard to find out about it, you have to end up reading the very last sentence in the README, and it is kind of mentioned as a side note. Therefore I tried to put a mention of it on more prominent place.
=> Emphasized dante-tap-type-time in README

dante.el
Partially reverts 7411904bfbde25cdb986e001ec682593dcb7c5e3
=> Use "cabal repl" instead of "cabal v1-repl" for bare-cabal

dante.el
It seems that haskell-mode has [made the `literate-haskell-mode` name obsolete
and aliased it to `haskell-literate-mode`](https://github.com/haskell/haskell-mode/blob/master/haskell-mode.el#L1001):
```elisp
(define-obsolete-function-alias 'literate-haskell-mode 'haskell-literate-mode "2020-04")
``` 
The alias seems to work for the most part, but doesn't seem to work with
flycheck checkers.  So this commit changes the name to the new name for the one
place Dante references it.
=> address usage of obsolete literate-haskell-mode
